/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type ReqCreateEvent struct {

	Title string `json:"title"`

	Description string `json:"description,omitempty"`

	Tags []string `json:"tags,omitempty"`

	Type string `json:"type"`

	StartTime time.Time `json:"start_time"`

	EndTime time.Time `json:"end_time,omitempty"`

	DueDate string `json:"due_date,omitempty"`

	Status string `json:"status,omitempty"`

	Priority string `json:"priority,omitempty"`

	CategoryId int32 `json:"category_id,omitempty"`

	IsAllDay bool `json:"is_all_day,omitempty"`
}
