/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type GetAiConversation200ResponseMessagesInner struct {

	Id string `json:"id"`

	ConversationId string `json:"conversation_id"`

	RunId string `json:"run_id"`

	Role string `json:"role"`

	Content string `json:"content"`

	Metadata map[string]interface{} `json:"metadata,omitempty"`

	CreatedAt time.Time `json:"created_at"`
}
