/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ListTemplates200Response struct {

	Templates []CreateTemplate201Response `json:"templates,omitempty"`
}
