/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type ListTemplates200ResponseTemplatesInner struct {

	Id string `json:"id"`

	Name string `json:"name"`

	Icon string `json:"icon"`

	Content string `json:"content"`

	Tags []string `json:"tags"`

	Color string `json:"color,omitempty"`

	UserId string `json:"user_id"`

	CreatedAt time.Time `json:"created_at"`

	UpdatedAt time.Time `json:"updated_at"`
}
