/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ReqCollabToken struct {

	NoteId string `json:"note_id"`

	EditToken string `json:"edit_token,omitempty"`
}
