/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type EventsListGet200Response struct {

	Data []ResDetailEvent `json:"data,omitempty"`
}
