/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type User struct {

	// User UUID
	Id string `json:"id"`

	Username string `json:"username"`

	Name string `json:"name"`

	Email string `json:"email"`

	Avatar string `json:"avatar"`

	AvatarUrl string `json:"avatar_url"`

	Status string `json:"status"`

	EmailVerified bool `json:"email_verified"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
