/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type User struct {

	// User UUID
	Id string `json:"id"`

	Name string `json:"name"`

	Email string `json:"email"`

	Avatar string `json:"avatar"`

	CreatedAt time.Time `json:"created_at"`

	UpdatedAt time.Time `json:"updated_at"`
}
