/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ReqReorderFolders struct {

	// Parent folder ID. Use empty string for root folders.
	ParentId string `json:"parent_id,omitempty"`

	FolderIds []string `json:"folder_ids"`
}
