/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ReqInlineEdit struct {

	WorkspaceId string `json:"workspace_id"`

	NoteId string `json:"note_id,omitempty"`

	Action string `json:"action"`

	SelectedText string `json:"selected_text"`

	CustomPrompt string `json:"custom_prompt,omitempty"`

	ContextBlocks []map[string]interface{} `json:"context_blocks,omitempty"`
}
