/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ReqCreateNote struct {

	Title string `json:"title"`

	ContentType string `json:"content_type"`

	Status string `json:"status"`

	Content string `json:"content"`

	Thumbnail string `json:"thumbnail"`

	Tags []string `json:"tags"`

	FolderId *string `json:"folder_id,omitempty"`

	IsPublic bool `json:"is_public"`
}
