/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ResProvideAiRunConsent struct {

	Ok bool `json:"ok"`

	RunId string `json:"run_id"`

	ToolCallId string `json:"tool_call_id"`

	Approved bool `json:"approved"`
}
