/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type UpdateNoteTom200Response struct {

	Id string `json:"id,omitempty"`

	TopOfMind bool `json:"top_of_mind,omitempty"`
}
