/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type ResDetailEvent struct {

	// Unique event identifier
	Id string `json:"id"`

	// User who created the event
	UserId int32 `json:"user_id"`

	// Event title
	Title string `json:"title"`

	// Event description
	Description string `json:"description,omitempty"`

	// Event tags
	Tags []string `json:"tags,omitempty"`

	// Event type
	Type string `json:"type"`

	// Event start time
	StartTime time.Time `json:"start_time"`

	// Event end time (optional)
	EndTime time.Time `json:"end_time,omitempty"`

	// Due date (mainly for tasks)
	DueDate string `json:"due_date,omitempty"`

	// Status (only for tasks)
	Status string `json:"status,omitempty"`

	// Priority (only for tasks)
	Priority string `json:"priority,omitempty"`

	// Category ID
	CategoryId int32 `json:"category_id,omitempty"`

	// Whether event is all-day
	IsAllDay bool `json:"is_all_day,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
