/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type CreateTemplateRequest struct {

	Name string `json:"name"`

	Icon string `json:"icon"`

	Content string `json:"content"`

	Tags []string `json:"tags,omitempty"`

	Color string `json:"color,omitempty"`
}
