/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ReqUpdateProfile struct {

	Name string `json:"name,omitempty"`

	Email string `json:"email,omitempty"`

	Avatar string `json:"avatar,omitempty"`
}
