/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type Comment struct {

	Id string `json:"id"`

	NoteId string `json:"note_id"`

	UserId string `json:"user_id"`

	UserName string `json:"user_name"`

	UserAvatar string `json:"user_avatar,omitempty"`

	ParentId *string `json:"parent_id,omitempty"`

	Content string `json:"content"`

	CreatedAt time.Time `json:"created_at"`

	UpdatedAt time.Time `json:"updated_at"`

	Replies []Comment `json:"replies,omitempty"`
}
