/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ResUploadedMedia struct {

	// Public URL of the uploaded image
	Url string `json:"url"`

	// Object key stored in the R2 bucket
	Key string `json:"key"`

	// MIME type stored alongside the object
	ContentType string `json:"contentType"`

	// Final object size in bytes after resizing and recompression
	Size int64 `json:"size"`

	// Original image format detected before processing
	OriginalFormat string `json:"originalFormat,omitempty"`
}
