/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ReqCreateAiRun struct {

	WorkspaceId string `json:"workspace_id"`

	SessionId string `json:"session_id"`

	NoteId string `json:"note_id,omitempty"`

	FolderId string `json:"folder_id,omitempty"`

	ConversationId string `json:"conversation_id,omitempty"`

	DisplayUserMessage string `json:"display_user_message,omitempty"`

	Message ReqCreateAiRunMessage `json:"message"`
}
