/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ListFolders200Response struct {

	Folders []ResDetailFolder `json:"folders,omitempty"`

	// Total number of folders
	Total int32 `json:"total,omitempty"`

	// Number of folders per page
	Limit int32 `json:"limit,omitempty"`

	// Number of folders skipped
	Offset int32 `json:"offset,omitempty"`
}
