/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ListComments200Response struct {

	Comments []ListComments200ResponseCommentsInner `json:"comments,omitempty"`

	// Total number of comments
	Total int32 `json:"total,omitempty"`
}
