/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type ResDetailNote struct {

	Id string `json:"id"`

	Title string `json:"title"`

	Content string `json:"content"`

	ContentType string `json:"content_type"`

	Status string `json:"status"`

	TopOfMind bool `json:"top_of_mind"`

	Thumbnail string `json:"thumbnail"`

	Tags []string `json:"tags"`

	FolderId *string `json:"folder_id,omitempty"`

	IsPublic bool `json:"is_public"`

	PublicEditEnabled bool `json:"public_edit_enabled,omitempty"`

	PublicEditToken string `json:"public_edit_token,omitempty"`

	CreatedAt time.Time `json:"created_at"`

	UpdatedAt time.Time `json:"updated_at"`
}
