/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ListNotes200Response struct {

	Notes []ResDetailNote `json:"notes,omitempty"`

	// Total number of notes
	Total int32 `json:"total,omitempty"`

	// Number of notes per page
	Limit int32 `json:"limit,omitempty"`

	// Number of notes skipped
	Offset int32 `json:"offset,omitempty"`

	// Query to search for
	Query string `json:"query,omitempty"`
}
