/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ReorderFolders200Response struct {

	Ok bool `json:"ok"`

	ParentId string `json:"parent_id"`

	FolderIds []string `json:"folder_ids"`
}
