/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ReqCreateAiRun struct {

	WorkspaceId string `json:"workspace_id"`

	SessionId string `json:"session_id"`

	NoteId string `json:"note_id"`

	Message ReqCreateAiRunMessage `json:"message"`
}
