/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type ResNoteSnapshot struct {

	Id string `json:"id"`

	UpdatedAt time.Time `json:"updated_at"`
}
