/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ResCollabTokenNote struct {

	Id string `json:"id"`

	Title string `json:"title"`

	Content string `json:"content"`

	Tags []string `json:"tags"`

	IsPublic bool `json:"is_public"`

	PublicEditEnabled bool `json:"public_edit_enabled"`
}
