/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ReqUpdateNote struct {

	Id string `json:"id"`

	Title string `json:"title,omitempty"`

	Content string `json:"content,omitempty"`

	ContentType string `json:"content_type,omitempty"`

	Status string `json:"status,omitempty"`

	Thumbnail string `json:"thumbnail,omitempty"`

	Tags []string `json:"tags,omitempty"`

	FolderId *string `json:"folder_id,omitempty"`

	IsPublic bool `json:"is_public,omitempty"`
}
