/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type ListComments200ResponseCommentsInner struct {

	Id string `json:"id,omitempty"`

	NoteId string `json:"note_id,omitempty"`

	UserId string `json:"user_id,omitempty"`

	UserName string `json:"user_name,omitempty"`

	UserAvatar string `json:"user_avatar,omitempty"`

	Content string `json:"content,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
