/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handlers

import (
	"github.com/duckviet/gin-collaborative-editor/backend/internal/service"
	"github.com/gin-gonic/gin"
)

type NoteAPI struct {
	noteService service.NoteService
}

// Post /api/v1/notes
// Create a new note 
func (api *NoteAPI) CreateNote(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /api/v1/notes/:id/delete
// Delete note by ID 
func (api *NoteAPI) DeleteNote(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/v1/notes/:id
// Get note by ID 
func (api *NoteAPI) GetNote(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/v1/notes/list
// List user's notes 
func (api *NoteAPI) ListNotes(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /api/v1/notes/:id/update
// Update note by ID 
func (api *NoteAPI) UpdateNote(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

