/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handlers

import (
	"github.com/duckviet/gin-collaborative-editor/backend/internal/service"
	"github.com/gin-gonic/gin"
)

type AuthAPI struct {
	authService service.AuthService
}

// Get /api/v1/auth/check
// Check current JWT and return basic info 
func (api *AuthAPI) CheckAuth(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/v1/auth/login
// Authenticate to receive a JWT 
func (api *AuthAPI) Login(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/v1/auth/logout
// Logout and invalidate JWT 
func (api *AuthAPI) Logout(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/v1/auth/register
// Register a new user 
func (api *AuthAPI) Register(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

