/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handlers

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/duckviet/gin-collaborative-editor/backend/internal/config"
	"github.com/duckviet/gin-collaborative-editor/backend/internal/dto"
	"github.com/duckviet/gin-collaborative-editor/backend/internal/service"
	"github.com/gin-gonic/gin"
)

type AuthAPI struct {
	authService service.AuthService
	config      *config.Config
}

// NewAuthAPI creates a new AuthAPI instance
func NewAuthAPI(authService service.AuthService, cfg *config.Config) *AuthAPI {
	return &AuthAPI{
		authService: authService,
		config:      cfg,
	}
}

// Get /api/v1/auth/check
// Check current JWT and return basic info 
func (api *AuthAPI) CheckAuth(c *gin.Context) {
	// Lấy token từ header Authorization: Bearer <token>
	authHeader := c.GetHeader("Authorization")
	if authHeader == "" {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "missing Authorization header"})
		return
	}

	token := strings.TrimPrefix(authHeader, "Bearer ")
	token = strings.TrimSpace(token)
	if token == "" {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "missing token"})
		return
	}

	user, err := api.authService.ValidateToken(c.Request.Context(), token)
	if err != nil {
		c.JSON(http.StatusUnauthorized, gin.H{"error": err.Error()})
		return
	}
	// Trả về thông tin cơ bản của user
    c.JSON(http.StatusOK, gin.H{
        "id":       user.ID,
        "username": user.Username,
        "email":    user.Email,
        "name":     user.Name,
        "status":   user.Status,
    })
}

// Post /api/v1/auth/login
// Authenticate to receive a JWT 
func (api *AuthAPI) Login(c *gin.Context) {
	var req dto.ReqLoginCredentials
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid request, " + err.Error()})
		return
	}

	tokens, err := api.authService.Login(c.Request.Context(), req)
	if err != nil {
		c.JSON(http.StatusUnauthorized, gin.H{"error": err.Error()})
		return
	}
	fmt.Println("AccessToken:", tokens.AccessToken)
	fmt.Println("RefreshToken:", tokens.RefreshToken)

	// Set HttpOnly cookies (security best practice)
	setAuthCookies(c, api.config, tokens.AccessToken, tokens.RefreshToken)

	// Return tokens in response body for backward compatibility
	// Frontend axios interceptor needs tokens to set Authorization header
	// HttpOnly cookies are used by middleware for server-side auth check
	c.JSON(http.StatusOK, tokens)
}

// Post /api/v1/auth/logout
// Logout and invalidate JWT 
func (api *AuthAPI) Logout(c *gin.Context) {
	// Try to get token from Authorization header or cookie
	token := extractTokenFromRequest(c)
	if token == "" {
		// If no token, still clear cookies and return success
		clearAuthCookies(c, api.config)
		c.JSON(http.StatusOK, gin.H{"message": "logout successful"})
		return
	}

	// Invalidate token in backend
	err := api.authService.Logout(c.Request.Context(), token)
	if err != nil {
		// Even if logout fails, clear cookies
		clearAuthCookies(c, api.config)
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	// Clear HttpOnly cookies
	clearAuthCookies(c, api.config)

	c.JSON(http.StatusOK, gin.H{"message": "logout successful"})
}

// Post /api/v1/auth/register
// Register a new user 
func (api *AuthAPI) Register(c *gin.Context) {
	var req dto.ReqUserRegistration
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid request, " + err.Error()})
		return
	}

	tokens, err := api.authService.Register(c.Request.Context(), req)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// Set HttpOnly cookies (security best practice)
	setAuthCookies(c, api.config, tokens.AccessToken, tokens.RefreshToken)

	// Return tokens in response body for backward compatibility
	// HttpOnly cookies are used by middleware for server-side auth check
	c.JSON(http.StatusCreated, tokens)
}

// Post /api/v1/auth/refresh-token
// Refresh a JWT 
func (api *AuthAPI) RefreshToken(c *gin.Context) {
	var req dto.RefreshTokenRequest

	// 1. Lấy Token: Ưu tiên Cookie (vì HttpOnly an toàn hơn), sau đó mới đến Body
	refreshToken := getRefreshTokenFromCookie(c)
	
	if refreshToken == "" {
		// Nếu cookie không có, thử đọc từ Body (để hỗ trợ các client khác như Mobile)
		if err := c.ShouldBindJSON(&req); err == nil {
			refreshToken = req.RefreshToken
		}
	}

	// Nếu cuối cùng vẫn không có token
	if refreshToken == "" {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "missing refresh token"})
		return
	}

	// 2. Gọi Service để verify và tạo cặp token mới
	tokens, err := api.authService.RefreshToken(c.Request.Context(), refreshToken)
	if err != nil {
		// QUAN TRỌNG: Nếu token hết hạn hoặc không hợp lệ, xóa luôn Cookie cũ 
		// để trình duyệt sạch sẽ và trả về 401.
		clearAuthCookies(c, api.config) 
		
		// Trả về 401 để Axios Interceptor bên Frontend biết đường mà Redirect sang /auth
		c.JSON(http.StatusUnauthorized, gin.H{"error": "invalid or expired refresh token"})
		return
	}

	// 3. Set cặp HttpOnly cookies mới (Access Token & Refresh Token)
	// Việc set Access Token vào Cookie giúp Middleware Next.js đọc được.
	setAuthCookies(c, api.config, tokens.AccessToken, tokens.RefreshToken)

	// Set thêm một cookie thường (HttpOnly=false) làm "cờ hiệu" cho Frontend JS
	c.SetCookie("is_logged_in", "true", 3600*24*7, "/", "", false, false)

	// 4. Trả về tokens trong response body
	c.JSON(http.StatusOK, tokens)
}
