/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handlers

import (
	"net/http"

	"github.com/duckviet/gin-collaborative-editor/backend/internal/service"
	"github.com/gin-gonic/gin"
)

type MediaAPI struct {
	mediaService service.MediaService
}

func NewMediaAPI(mediaService service.MediaService) *MediaAPI {
	return &MediaAPI{mediaService: mediaService}
}

// Post /api/v1/media/upload
// Upload image to Cloudflare R2
func (api *MediaAPI) UploadMedia(c *gin.Context) {
	if api.mediaService == nil {
		c.JSON(http.StatusServiceUnavailable, gin.H{"error": "media service unavailable"})
		return
	}

	fileHeader, err := c.FormFile("file")
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "file is required"})
		return
	}

	file, err := fileHeader.Open()
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "cannot open file"})
		return
	}
	defer file.Close()

	result, err := api.mediaService.UploadImage(c.Request.Context(), file)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusCreated, result)
}
