/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handlers

import (
	"github.com/duckviet/gin-collaborative-editor/backend/internal/service"
	"github.com/gin-gonic/gin"
)

type FolderAPI struct {
	folderService service.FolderService
}

// Post /api/v1/folders/:id/add-note
// Add note to folder 
func (api *FolderAPI) AddNoteToFolder(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/v1/folders/create
// Create a new folder 
func (api *FolderAPI) CreateFolder(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /api/v1/folders/:id/delete
// Delete folder by ID 
func (api *FolderAPI) DeleteFolder(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/v1/folders/:id
// Get folder by ID 
func (api *FolderAPI) GetFolder(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/v1/folders/list
// List user's folders 
func (api *FolderAPI) ListFolders(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /api/v1/folders/:id/update
// Update folder by ID 
func (api *FolderAPI) UpdateFolder(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

