/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handlers

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the AuthAPI part of the API
	AuthAPI AuthAPI
	// Routes for the FolderAPI part of the API
	FolderAPI FolderAPI
	// Routes for the NoteAPI part of the API
	NoteAPI NoteAPI
	// Routes for the UserAPI part of the API
	UserAPI UserAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"CheckAuth",
			http.MethodGet,
			"/api/v1/auth/check",
			handleFunctions.AuthAPI.CheckAuth,
		},
		{
			"Login",
			http.MethodPost,
			"/api/v1/auth/login",
			handleFunctions.AuthAPI.Login,
		},
		{
			"Logout",
			http.MethodPost,
			"/api/v1/auth/logout",
			handleFunctions.AuthAPI.Logout,
		},
		{
			"Register",
			http.MethodPost,
			"/api/v1/auth/register",
			handleFunctions.AuthAPI.Register,
		},
		{
			"AddNoteToFolder",
			http.MethodPost,
			"/api/v1/folders/:id/add-note",
			handleFunctions.FolderAPI.AddNoteToFolder,
		},
		{
			"CreateFolder",
			http.MethodPost,
			"/api/v1/folders/create",
			handleFunctions.FolderAPI.CreateFolder,
		},
		{
			"DeleteFolder",
			http.MethodDelete,
			"/api/v1/folders/:id/delete",
			handleFunctions.FolderAPI.DeleteFolder,
		},
		{
			"GetFolder",
			http.MethodGet,
			"/api/v1/folders/:id",
			handleFunctions.FolderAPI.GetFolder,
		},
		{
			"ListFolders",
			http.MethodGet,
			"/api/v1/folders/list",
			handleFunctions.FolderAPI.ListFolders,
		},
		{
			"UpdateFolder",
			http.MethodPut,
			"/api/v1/folders/:id/update",
			handleFunctions.FolderAPI.UpdateFolder,
		},
		{
			"CreateNote",
			http.MethodPost,
			"/api/v1/notes",
			handleFunctions.NoteAPI.CreateNote,
		},
		{
			"DeleteNote",
			http.MethodDelete,
			"/api/v1/notes/:id/delete",
			handleFunctions.NoteAPI.DeleteNote,
		},
		{
			"GetNote",
			http.MethodGet,
			"/api/v1/notes/:id",
			handleFunctions.NoteAPI.GetNote,
		},
		{
			"ListNotes",
			http.MethodGet,
			"/api/v1/notes/list",
			handleFunctions.NoteAPI.ListNotes,
		},
		{
			"UpdateNote",
			http.MethodPut,
			"/api/v1/notes/:id/update",
			handleFunctions.NoteAPI.UpdateNote,
		},
		{
			"DeleteMe",
			http.MethodDelete,
			"/api/v1/user/delete",
			handleFunctions.UserAPI.DeleteMe,
		},
		{
			"GetMe",
			http.MethodGet,
			"/api/v1/user/me",
			handleFunctions.UserAPI.GetMe,
		},
		{
			"UpdateMe",
			http.MethodPatch,
			"/api/v1/user/update",
			handleFunctions.UserAPI.UpdateMe,
		},
	}
}
