import type { Metadata } from "next";
import { Geist_Mono, Inter, Noto_Serif } from "next/font/google";
import "./globals.css";
import { SidebarWrapper } from "@/widgets/sidebar";
import { QueryProvider } from "@/shared/providers/QueryProvider";
import { ThemeProvider } from "@/shared/providers/ThemeProvider";
import { AuthProvider, AutoLogin } from "@/features/auth";
import { AppearanceApplier } from "@/shared/providers/AppearanceApplier";
import { GlobalDndProvider } from "@/shared/components/dnd/GlobalDndProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const notoSerif = Noto_Serif({
  variable: "--font-noto-serif",
  subsets: ["vietnamese", "latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/mindnotion-metadata.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${geistMono.variable} ${notoSerif.variable}`}
      suppressHydrationWarning
    >
      <body className="antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppearanceApplier />
          <QueryProvider>
            <AutoLogin>
              <AuthProvider>
                <GlobalDndProvider>
                  <SidebarWrapper>{children}</SidebarWrapper>
                </GlobalDndProvider>
              </AuthProvider>
            </AutoLogin>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
