openapi: 3.0.3
info:
  title: Modular JWT Authenticated API
  version: 1.0.0
  description: An example API using JWT imported from a separate file.
servers:
  - url: 'http://localhost:8080/api/v1'
security:
  - BearerAuth: []
paths:
  /auth/login:
    post:
      summary: Authenticate to receive a JWT
      operationId: login
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginCredentials'
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokens'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /auth/register:
    post:
      summary: Register a new user
      operationId: register
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokens'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /auth/logout:
    post:
      summary: Logout and invalidate JWT
      operationId: logout
      tags:
        - Auth
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Logout successful
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /auth/check:
    get:
      summary: Check current JWT and return basic info
      operationId: checkAuth
      tags:
        - Auth
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Token is valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokens'
        '401':
          $ref: '#/components/responses/Unauthorized'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Enter your JWT token in the format: Bearer <token>.
        The token can be obtained from the `/auth/login` endpoint.
  schemas:
    AuthTokens:
      type: object
      properties:
        access_token:
          type: string
          example: eyJhbGciOiJI...
        refresh_token:
          type: string
          example: def50200...
    LoginCredentials:
      type: object
      properties:
        username:
          type: string
          example: johndoe
        password:
          type: string
          format: password
          example: strongpassword123
      required:
        - username
        - password
    UserRegistration:
      type: object
      properties:
        username:
          type: string
          example: janedoe
        password:
          type: string
          format: password
          example: anotherstrongpassword
        email:
          type: string
          format: email
          example: jane.doe@example.com
      required:
        - username
        - password
        - email
    Asset:
      type: object
      required:
        - id
        - name
        - uri
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: my_first_asset
        uri:
          type: string
          format: uri
          example: 's3://my-bucket/data.csv'
  responses:
    BadRequest:
      description: Bad Request. The request is invalid.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Invalid request.
    Unauthorized:
      description: 'Unauthorized. The provided JWT token is missing, invalid, or expired.'
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Authentication token is required.
    NotFound:
      description: Not Found. The requested resource was not found.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Resource not found.
    InternalServerError:
      description: Internal Server Error. The server encountered an unexpected condition that prevented it from fulfilling the request.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Internal server error.
  parameters:
    LimitParam:
      name: limit
      in: query
      description: Maximum number of results to return.
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
    OffsetParam:
      name: offset
      in: query
      description: Number of results to skip for pagination.
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0
