// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// AuthTokens defines model for AuthTokens.
type AuthTokens struct {
	AccessToken  *string `json:"access_token,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// LoginCredentials defines model for LoginCredentials.
type LoginCredentials struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// UserRegistration defines model for UserRegistration.
type UserRegistration struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Username string              `json:"username"`
}

// BadRequest defines model for BadRequest.
type BadRequest struct {
	Error *string `json:"error,omitempty"`
}

// Unauthorized defines model for Unauthorized.
type Unauthorized struct {
	Error *string `json:"error,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginCredentials

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = UserRegistration

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check current JWT and return basic info
	// (GET /auth/check)
	CheckAuth(ctx echo.Context) error
	// Authenticate to receive a JWT
	// (POST /auth/login)
	Login(ctx echo.Context) error
	// Logout and invalidate JWT
	// (POST /auth/logout)
	Logout(ctx echo.Context) error
	// Register a new user
	// (POST /auth/register)
	Register(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CheckAuth converts echo context to params.
func (w *ServerInterfaceWrapper) CheckAuth(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CheckAuth(ctx)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// Register converts echo context to params.
func (w *ServerInterfaceWrapper) Register(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Register(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/auth/check", wrapper.CheckAuth)
	router.POST(baseURL+"/auth/login", wrapper.Login)
	router.POST(baseURL+"/auth/logout", wrapper.Logout)
	router.POST(baseURL+"/auth/register", wrapper.Register)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RW32/bNhD+Vwhuj4IkJxtQ6GlpsQ0JNmzIXPQhMVaaPFtMJZI7Um69wv/7cKQUS7Ga",
	"df2RvfGHeHffd9/d6T2XtnXWgAmeV+85gnfWeIib50Jdw18d+EA7aU0AE5fCuUZLEbQ1xZ23hs68rKEV",
	"tHJoHWDQyQggWoyLd6J1DfCKX5qdaLRimIznPONh7+jGB9Rmyw+H+xO7vgMZ+IGOFHiJ2pFbXlF0rA8v",
	"Z8saBnNMe6aTh5wfMv7SiC7UFvXfoL4sjosu1GBCb4EF+wYMeadANIL6RGDjgBMyh3anFSh29Wp5dNNq",
	"77XZZgPajFlk8M4l12Q3YYnhU6xLeulPoQkpwfs/o+EpQthf1eufpf5NX13m+QyejCNsEHw991rB5vvy",
	"rCxnX54ykfFf7FabFwiKWBXNTKhOeP/Wopo68gGt2Q53i7NznvGNxVYEXh2fzATfeUAjWpiau7O1URZm",
	"Yx5yy6ub4+vs6GQ1A+ulB7yGrfYBRcrxibhaoZsHQQgDubLwQ3+US9uOYaUnM5jmKRLGhhpwytRn0iQM",
	"fCpNWR//KV0kW5Ad6rD/g+TbtyIQCEgipt067n4aQr96teQPi+hHEwDZ3nY4LhrDQg0sYa5YMspuu7I8",
	"l/GLuIT81lDVpTdSGLYGZtdBaAOKbdC20crrgsq0aEizrxkY5aw2Ib81vC88QpUiPVJUh+BSzWuzsYRl",
	"GvaFYT3B7OL3S9ZRgUcAunUWw+BfMA9OoAjANrqBWF46xKz8alXXiIR61KBAkUGe8R2gT74WeZmXlF7r",
	"wAinecXP8zI/j3kKdeQ9YZQ1yDe03ULsmyTdqORLxSv+gm5jarLp/Dgry//UcL9F2PCKf1McZ1LRt7Bi",
	"1L9mWuZy6ImxERKm78rFh0zex1hMRsNYeby6mWruZnVYZdx3bStwP2BmskMEEyLXwtBACx0athZeSxYT",
	"nPEgtp6qINpZkZORbmInsH6G1NgKeSok8OG5VfsvxuVJmz1MSzZgB4f/LZcPpqrv4nTadM1npPU+b+OK",
	"YMEyBAl6B0yw1EQeyZbtwqPpovt50qb40qcnuMp/xzX6H/v6Cu/DJFn3/xdE2eMsYRxygB/m6Xr44uso",
	"+2TSfpSyF0+kbIqODRyBGkmg2T+tCO6zPOSDCWbgLaNRPZPfj9ANIA2WeNth00+6qigaK0VTWx+qZ+Wz",
	"shBOF7sFP6wO/wQAAP//yv9KqnoMAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
