/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type ResDetailFolder struct {

	Id string `json:"id"`

	Name string `json:"name"`

	ParentId string `json:"parent_id"`

	IsPublic bool `json:"is_public"`

	Notes []string `json:"notes"`

	ChildrenFolders []string `json:"children_folders"`

	CreatedAt time.Time `json:"created_at"`

	UpdatedAt time.Time `json:"updated_at"`
}
