/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type ResDetailNote struct {

	Id string `json:"id"`

	Title string `json:"title"`

	Content string `json:"content"`

	Thumbnail string `json:"thumbnail"`

	Tags []string `json:"tags"`

	IsPublic bool `json:"is_public"`

	CreatedAt time.Time `json:"created_at"`

	UpdatedAt time.Time `json:"updated_at"`
}
