/*
 * Modular JWT Authenticated API
 *
 * An example API using JWT imported from a separate file.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handlers

import (
	"net/http"

	dbmodels "github.com/duckviet/gin-collaborative-editor/backend/internal/database/models"

	"github.com/duckviet/gin-collaborative-editor/backend/internal/service"
	"github.com/gin-gonic/gin"
)

type UserAPI struct {
	userService service.UserService
}

// Delete /api/v1/user/delete
// Delete current user 
func (api *UserAPI) DeleteMe(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/v1/user/me
// Get current user information 
func (api *UserAPI) GetMe(c *gin.Context) {
	userVal, ok := c.Get("user")
    if !ok {
        c.JSON(http.StatusUnauthorized, gin.H{"error": "unauthorized"})
        return
    }
    u := userVal.(*dbmodels.User)

	c.JSON(200, gin.H{
		"id": u.ID,
		"username": u.Username,
		"email": u.Email,
		"name": u.Name,
		"status": u.Status,
	})
}

// Patch /api/v1/user/update
// Update current user information 
func (api *UserAPI) UpdateMe(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

